-- LEGO Cloud: Supabase setup for cross-device sync
-- Run this in Supabase SQL Editor.

-- 1) Tables
create table if not exists public.collection (
  id bigint generated by default as identity primary key,
  set_number text not null,
  owner_profile text not null default 'shared',
  name text not null default '',
  year integer,
  theme text not null default '',
  num_parts integer not null default 0,
  set_img_url text not null default '',
  manual_url text not null default '',
  storage_location text not null default '',
  owned boolean not null default false,
  has_box boolean not null default false,
  has_manual boolean not null default false,
  missing_pieces integer not null default 0,
  selling_status text,
  asking_price numeric not null default 0,
  sale_platforms jsonb not null default '[]'::jsonb,
  build_status text,
  seal_status text not null default 'Åbnet',
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.missing_parts (
  id bigint generated by default as identity primary key,
  set_number text not null,
  owner_profile text not null default 'shared',
  part_num text not null,
  color text not null default '',
  quantity_missing integer not null default 1,
  part_name text not null default '',
  part_image text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 2) Constraints + indexes
create unique index if not exists ux_collection_set_owner
  on public.collection (set_number, owner_profile);

create unique index if not exists ux_missing_parts_unique_row
  on public.missing_parts (set_number, owner_profile, part_num, color);

create index if not exists ix_collection_owner_profile
  on public.collection (owner_profile);

create index if not exists ix_missing_parts_owner_profile
  on public.missing_parts (owner_profile);

-- 3) Auto-update updated_at
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_collection_touch_updated_at on public.collection;
create trigger trg_collection_touch_updated_at
before update on public.collection
for each row
execute function public.touch_updated_at();

drop trigger if exists trg_missing_parts_touch_updated_at on public.missing_parts;
create trigger trg_missing_parts_touch_updated_at
before update on public.missing_parts
for each row
execute function public.touch_updated_at();

-- 4) Realtime support
alter table public.collection replica identity full;
alter table public.missing_parts replica identity full;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'collection'
  ) then
    alter publication supabase_realtime add table public.collection;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'missing_parts'
  ) then
    alter publication supabase_realtime add table public.missing_parts;
  end if;
end
$$;

-- 5) RLS (simple/open for anon + authenticated)
alter table public.collection enable row level security;
alter table public.missing_parts enable row level security;

drop policy if exists "collection_select_all" on public.collection;
create policy "collection_select_all"
on public.collection
for select
to anon, authenticated
using (true);

drop policy if exists "collection_insert_all" on public.collection;
create policy "collection_insert_all"
on public.collection
for insert
to anon, authenticated
with check (true);

drop policy if exists "collection_update_all" on public.collection;
create policy "collection_update_all"
on public.collection
for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "collection_delete_all" on public.collection;
create policy "collection_delete_all"
on public.collection
for delete
to anon, authenticated
using (true);

drop policy if exists "missing_parts_select_all" on public.missing_parts;
create policy "missing_parts_select_all"
on public.missing_parts
for select
to anon, authenticated
using (true);

drop policy if exists "missing_parts_insert_all" on public.missing_parts;
create policy "missing_parts_insert_all"
on public.missing_parts
for insert
to anon, authenticated
with check (true);

drop policy if exists "missing_parts_update_all" on public.missing_parts;
create policy "missing_parts_update_all"
on public.missing_parts
for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "missing_parts_delete_all" on public.missing_parts;
create policy "missing_parts_delete_all"
on public.missing_parts
for delete
to anon, authenticated
using (true);
